'use strict';
require('aws-sdk/lib/maintenance_mode_message').suppress = true;
const fs= require('fs');
// tests for hello
// Generated by serverless-jest-plugin

const mod = require('./../../../src/function/document/ocr/index');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

const testBucket = process.env.TEST_BUCKET;
const testFile = process.env.TEST_FILE;

describe('ocr', () => {

    beforeAll((done) => {
        //lambdaWrapper.init(liveFunction); // Run the deployed lambda
        done();
    });

    /**
     * This function test ocr process via Textract
     * You can pass any bucket name and image key
     * It will run the lambda function which normally would be triggered by s3 upload
     * You can check result in "response.json" created in __tests__/document/ocr folder
     * You can also check result in the same folder in which you upload the test image
     * This image will be deleted and replaced by the result json with the same name of the image
     */
    it('Test ocr process', () => {
        return wrapped.run({
            "Records": [
                {
                    "s3": {
                        "bucket": {
                            "name": testBucket,
                        },
                        "object": {
                            "key": "test/"+testFile,
                        }
                    }
                }
            ]
        }).then((response) => {
            //Expect response to be defined
            expect(response).toBeDefined();
            //Validate status
            expect(response.statusCode).toEqual(200);

            fs.writeFile(
                '__tests__/document/ocr/response.json',
                response.body,
                'utf8',
                function(err) {
                    if (err) throw err;
                }
            );
        });
    });
});
