version: ${env:STAGE_NAME}
servers:
    - url: my-api
      description: ${env:STAGE_NAME}
title: 'My API'
description: 'My API'
models:
  #ERRORS
  - name: "BadRequestResponse"
    description: "Bad/Invalid request error response"
    contentType: "application/json"
    schema: ${file(./doc/models/BadRequestResponse.yml)}
  - name: "ErrorResponse"
    description: "Generic error response"
    contentType: "application/json"
    schema: ${file(./doc/models/ErrorResponse.yml)}
  #DOCUMENT
  - name: "DocumentResponse"
    description: "Document response model"
    contentType: "application/json"
    schema: ${file(./doc/models/DocumentResponse.yml)}



